### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by Absolucy** [NurMarvin/discord-proxy#2]
Docker command used to run:

`docker -- run -d -p 3333:3333 --restart unless-stopped -e CANONICAL_URL=http://127.0.0.1:3333 nurmarvin/discord-proxy`

Error in console:

`Access to XMLHttpRequest at 'https://discord-attachments-uploads-prd.storage.googleapis.com/[uuid]/golf.gif?upload_id=[id]' from origin 'http://127.0.0.1:3333' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://canary.discord.com' that is not equal to the supplied origin.`

**Comment by asportnoy** [comment]
You need to run Discord with `--disable-web-security`. See https://gist.github.com/mugman174/0a59efe2733407d2041449a0e5815d66#discord-executable to find where your Discord executable is located

**Comment by Absolucy** [comment]
Ah, okay. I was running the *updater* with `--disable-web-security`, oops.
